import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Html,
  Img,
  Preview,
  Section,
  Text,
  Hr,
} from '@react-email/components';
import * as React from 'react';

// Showcase data - real examples generated by BrandForge AI
// Note: Using different brands than TemplateShowcaseEmail to avoid repetition
const showcaseExamples = [
  {
    id: 'bloom-beauty',
    brandName: 'Bloom Beauty Bar',
    industry: 'Beauty Salon',
    description: 'Luxury beauty salon with transformative services',
    logo: 'https://brandforge.me/showcase/examples/bloom-beauty/logo.png',
    post: {
      image: 'https://brandforge.me/showcase/examples/bloom-beauty/posts/post-1-image.png',
      caption: 'Step into a world where beauty meets unparalleled luxury and every visit is a journey of transformation.',
      hashtags: '#LuxurySalon #BeautyPampering #HairTransformation #NailArtistry #PersonalizedBeauty #SalonExperience',
    },
  },
  {
    id: 'chic-boutique',
    brandName: 'Chic Boutique',
    industry: 'Fashion',
    description: 'Curated fashion boutique for modern women',
    logo: 'https://brandforge.me/showcase/examples/chic-boutique/logo.png',
    post: {
      image: 'https://brandforge.me/showcase/examples/chic-boutique/posts/post-1-image.png',
      caption: 'Imagine a wardrobe that truly reflects you – unique, high-quality, and effortlessly chic.',
      hashtags: '#FashionBoutique #ContemporaryFashion #TimelessStyle #WomensFashion #CuratedStyle #PersonalizedShopping',
    },
  },
  {
    id: 'glow-skincare',
    brandName: 'Glow Skincare',
    industry: 'Skincare',
    description: 'Natural skincare products for radiant skin',
    logo: 'https://brandforge.me/showcase/examples/glow-skincare/logo.png',
    post: {
      image: 'https://brandforge.me/showcase/examples/glow-skincare/posts/post-1-image.png',
      caption: 'Ready to embrace naturally radiant, glowing skin.',
      hashtags: '#NaturalSkincare #RadiantSkin #SkincareRoutine #GlowingSkin #CleanBeauty',
    },
  },
];

interface ExampleShowcaseEmailProps {
  userName?: string;
  quickStartUrl?: string;
  industry?: string;
}

export const ExampleShowcaseEmail = ({
  userName = 'there',
  quickStartUrl = 'https://brandforge.me/quick-start',
  industry = 'business',
}: ExampleShowcaseEmailProps) => {
  return (
    <Html>
      <Head />
      <Preview>See what {industry} brands created with BrandForge AI in 30 seconds</Preview>
      <Body style={main}>
        <Container style={container}>
          {/* Logo/Header */}
          <Section style={header}>
            <div style={logoContainer}>
              <Text style={logoText}>✨ BrandForge AI</Text>
            </div>
          </Section>

          {/* Hero Section */}
          <Section style={heroSection}>
            <Heading style={h1}>Still on the fence{userName ? `, ${userName}` : ''}?</Heading>
            <Text style={heroText}>
              Check out what other {industry} brands created with BrandForge AI — in under a minute.
            </Text>
          </Section>

          {/* Example Posts Section */}
          <Section style={contentSection}>
            <Text style={sectionHeading}>🎨 Real Examples Created with BrandForge AI</Text>

            {showcaseExamples.map((example) => (
              <div key={example.id} style={exampleCard}>
                <div style={brandHeader}>
                  <Img
                    src={example.logo}
                    alt={example.brandName}
                    width="48"
                    height="48"
                    style={brandLogo}
                  />
                  <div>
                    <Text style={exampleLabel}>{example.brandName}</Text>
                    <Text style={exampleInput}>{example.description}</Text>
                  </div>
                </div>

                <div style={exampleResultBox}>
                  {/* Instagram-style Preview */}
                  <div style={instagramPreview}>
                    {/* Instagram Header */}
                    <div style={instagramHeader}>
                      <div style={instagramHeaderLeft}>
                        <div style={instagramAvatarRing}>
                          <Img
                            src={example.logo}
                            alt={example.brandName}
                            width="32"
                            height="32"
                            style={instagramAvatar}
                          />
                        </div>
                        <div>
                          <div style={instagramUsernameRow}>
                            <Text style={instagramUsername}>{example.brandName.toLowerCase().replace(/\s+/g, '')}</Text>
                            <span style={instagramVerified}>✓</span>
                          </div>
                          <Text style={instagramSponsored}>Sponsored</Text>
                        </div>
                      </div>
                      <Text style={instagramMenuDots}>⋯</Text>
                    </div>

                    {/* Instagram Post Image */}
                    <Img
                      src={example.post.image}
                      alt={`${example.brandName} post`}
                      width="100%"
                      style={postImage}
                    />

                    {/* Instagram Actions */}
                    <div style={instagramActions}>
                      <div style={instagramActionIcons}>
                        <span style={instagramIcon}>❤️</span>
                        <span style={instagramIcon}>💬</span>
                        <span style={instagramIcon}>📤</span>
                      </div>
                      <span style={instagramIcon}>🔖</span>
                    </div>

                    {/* Instagram Engagement & Caption */}
                    <div style={instagramCaptionArea}>
                      <Text style={instagramLikes}>1,234 likes</Text>
                      <Text style={instagramCaption}>
                        <strong style={instagramCaptionUsername}>{example.brandName.toLowerCase().replace(/\s+/g, '')}</strong>{' '}
                        {example.post.caption.substring(0, 125)}{example.post.caption.length > 125 ? '... ' : ' '}
                        {example.post.caption.length > 125 && <span style={instagramMore}>more</span>}
                      </Text>
                      <Text style={exampleHashtags}>{example.post.hashtags}</Text>
                      <Text style={instagramViewComments}>View all 42 comments</Text>
                      <Text style={instagramTime}>2 HOURS AGO</Text>
                    </div>
                  </div>

                  <Text style={generationBadge}>✨ Generated in 30 seconds</Text>
                </div>
              </div>
            ))}

            <Hr style={divider} />

            <Text style={text}>
              <strong>All of these were created in under 60 seconds.</strong> No design skills. No writing experience. Just describe your business and let AI do the rest.
            </Text>
          </Section>

          {/* CTA Section */}
          <Section style={ctaSection}>
            <Text style={ctaText}>Ready to create yours?</Text>
            <Button style={button} href={quickStartUrl}>
              Try Quick Start Now →
            </Button>
            <Text style={subText}>Takes 30 seconds. No credit card required.</Text>
          </Section>

          {/* Footer */}
          <Section style={footer}>
            <Text style={footerText}>
              Have questions? Just reply to this email — we read every message.
            </Text>
            <Hr style={divider} />
            <Text style={footerText}>
              BrandForge AI - AI-Powered Brand Content Generation
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

export default ExampleShowcaseEmail;

// Styles
const main = {
  backgroundColor: '#f6f9fc',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
  maxWidth: '600px',
};

const header = {
  padding: '32px 48px',
  textAlign: 'center' as const,
};

const logoContainer = {
  display: 'inline-block',
  padding: '12px 24px',
  backgroundColor: '#7C3AED',
  borderRadius: '8px',
};

const logoText = {
  color: '#ffffff',
  fontSize: '20px',
  fontWeight: 'bold',
  margin: '0',
};

const heroSection = {
  padding: '0 48px',
  textAlign: 'center' as const,
};

const h1 = {
  color: '#1a1a1a',
  fontSize: '28px',
  fontWeight: 'bold',
  margin: '0 0 16px',
  lineHeight: '1.3',
};

const heroText = {
  color: '#525252',
  fontSize: '18px',
  lineHeight: '1.6',
  margin: '0 0 32px',
};

const contentSection = {
  padding: '32px 48px',
};

const sectionHeading = {
  color: '#1a1a1a',
  fontSize: '20px',
  fontWeight: 'bold',
  margin: '0 0 24px',
  textAlign: 'center' as const,
};

const exampleCard = {
  backgroundColor: '#f9fafb',
  border: '1px solid #e5e7eb',
  borderRadius: '8px',
  padding: '20px',
  marginBottom: '20px',
};

const brandHeader = {
  display: 'flex',
  alignItems: 'center',
  gap: '12px',
  marginBottom: '16px',
};

const brandLogo = {
  borderRadius: '8px',
  objectFit: 'cover' as const,
};

const exampleLabel = {
  color: '#1a1a1a',
  fontSize: '16px',
  fontWeight: 'bold',
  margin: '0 0 4px',
};

const exampleInput = {
  color: '#6b7280',
  fontSize: '14px',
  margin: '0',
};

const exampleResultBox = {
  backgroundColor: '#ffffff',
  border: '2px solid #7C3AED',
  borderRadius: '6px',
  padding: '16px',
  overflow: 'hidden' as const,
};

const instagramPreview = {
  backgroundColor: '#ffffff',
  border: '1px solid #dbdbdb',
  borderRadius: '8px',
  overflow: 'hidden' as const,
  marginBottom: '12px',
};

const instagramHeader = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  padding: '12px 16px',
  borderBottom: '1px solid #efefef',
};

const instagramHeaderLeft = {
  display: 'flex',
  alignItems: 'center',
  gap: '10px',
};

const instagramAvatarRing = {
  padding: '2px',
  background: 'linear-gradient(45deg, #f09433 0%,#e6683c 25%,#dc2743 50%,#cc2366 75%,#bc1888 100%)',
  borderRadius: '50%',
  display: 'inline-block',
};

const instagramAvatar = {
  borderRadius: '50%',
  border: '2px solid #ffffff',
  display: 'block',
};

const instagramUsernameRow = {
  display: 'flex',
  alignItems: 'center',
  gap: '4px',
};

const instagramUsername = {
  fontSize: '14px',
  fontWeight: 'bold' as const,
  color: '#262626',
  margin: '0',
  display: 'inline-block',
};

const instagramVerified = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  width: '14px',
  height: '14px',
  backgroundColor: '#3897f0',
  borderRadius: '50%',
  color: '#ffffff',
  fontSize: '9px',
  fontWeight: 'bold' as const,
};

const instagramSponsored = {
  fontSize: '12px',
  color: '#8e8e8e',
  margin: '2px 0 0',
};

const instagramMenuDots = {
  fontSize: '24px',
  color: '#262626',
  fontWeight: 'bold' as const,
  margin: '0',
  transform: 'rotate(90deg)',
};

const postImage = {
  width: '100%',
  display: 'block',
  margin: '0',
};

const instagramActions = {
  padding: '12px 16px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  borderTop: '1px solid #efefef',
};

const instagramActionIcons = {
  display: 'flex',
  alignItems: 'center',
  gap: '16px',
};

const instagramIcon = {
  fontSize: '24px',
  display: 'inline-block',
};

const instagramCaptionArea = {
  padding: '0 16px 12px',
};

const instagramLikes = {
  fontSize: '14px',
  fontWeight: 'bold' as const,
  color: '#262626',
  margin: '0 0 8px',
};

const instagramCaption = {
  fontSize: '14px',
  color: '#262626',
  lineHeight: '1.5',
  margin: '0 0 4px',
};

const instagramCaptionUsername = {
  fontWeight: 'bold' as const,
};

const instagramMore = {
  color: '#8e8e8e',
  fontWeight: 'normal' as const,
};

const instagramViewComments = {
  fontSize: '14px',
  color: '#8e8e8e',
  margin: '8px 0 4px',
};

const instagramTime = {
  fontSize: '10px',
  color: '#8e8e8e',
  textTransform: 'uppercase' as const,
  letterSpacing: '0.5px',
  margin: '0',
};

const exampleCaption = {
  color: '#1a1a1a',
  fontSize: '14px',
  lineHeight: '1.6',
  margin: '0 0 12px',
  whiteSpace: 'pre-line' as const,
};

const exampleHashtags = {
  color: '#7C3AED',
  fontSize: '14px',
  margin: '0 0 12px',
};

const generationBadge = {
  display: 'inline-block',
  backgroundColor: '#FEF3C7',
  color: '#92400E',
  fontSize: '12px',
  fontWeight: 'bold',
  padding: '6px 12px',
  borderRadius: '4px',
  margin: '0',
};

const text = {
  color: '#525252',
  fontSize: '16px',
  lineHeight: '1.6',
  margin: '16px 0',
};

const ctaSection = {
  padding: '32px 48px',
  textAlign: 'center' as const,
};

const ctaText = {
  color: '#1a1a1a',
  fontSize: '20px',
  fontWeight: 'bold',
  margin: '0 0 24px',
};

const button = {
  backgroundColor: '#7C3AED',
  borderRadius: '8px',
  color: '#fff',
  fontSize: '16px',
  fontWeight: 'bold',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '14px 32px',
  margin: '0 0 16px',
};

const subText = {
  color: '#737373',
  fontSize: '14px',
  margin: '0',
};

const footer = {
  padding: '24px 48px',
  textAlign: 'center' as const,
};

const footerText = {
  color: '#737373',
  fontSize: '12px',
  lineHeight: '1.5',
  margin: '8px 0',
};

const divider = {
  borderColor: '#e5e7eb',
  margin: '24px 0',
};
