
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for BrandForge AI. Read the terms and conditions for using our application.',
  alternates: {
    canonical: '/terms-of-service',
  },
};


export default function TermsOfServicePage() {
  return (
    <Card className="shadow-lg">
      <CardHeader>
        <CardTitle className="text-3xl font-bold">Terms of Service</CardTitle>
        <CardDescription>Last Updated: {new Date().toLocaleDateString()}</CardDescription>
      </CardHeader>
      <CardContent className="prose prose-lg max-w-none prose-headings:font-bold prose-a:text-primary hover:prose-a:underline">
        
        <h2>1. Agreement to Terms</h2>
        <p>
            By using BrandForge AI (the "Application"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Application.
        </p>

        <h2>2. Intellectual Property Rights</h2>
        <p>
            <strong>Your Content:</strong> You retain all ownership rights to the brand information, prompts, and other content you submit to the Application ("Your Content").
        </p>
        <p>
            <strong>Generated Content:</strong> Subject to your compliance with these Terms, we hereby assign to you all our right, title, and interest in and to the images, text, and other materials generated by the AI based on Your Content ("Generated Content"). You are responsible for ensuring that the Generated Content does not infringe upon any third-party rights and that it complies with the terms of the underlying AI models (e.g., Google AI). The AI may produce similar or identical content for other users, and we cannot guarantee uniqueness.
        </p>
        <p>
            <strong>Application IP:</strong> The Application itself, including its "look and feel," source code, branding, the name "BrandForge AI," and our logos are our exclusive property. You may not duplicate, copy, or reuse any portion of the HTML/CSS, Javascript, or visual design elements without our express written permission.
        </p>
        
        <h2>3. User Accounts</h2>
        <p>
            You are responsible for safeguarding your account information and for any activities or actions under your account. You agree to notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
        </p>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to use the Application to create any harmful, illegal, or infringing content. This includes, but is not limited to, content that is:</p>
        <ul>
            <li>Defamatory, obscene, pornographic, or hateful.</li>
            <li>Infringing on the intellectual property rights of others.</li>
            <li>Used for generating spam, malware, or other malicious code.</li>
            <li>Deceptive, fraudulent, or for the purpose of promoting disinformation.</li>
        </ul>
        <p>We reserve the right to suspend or terminate your account for any violation of these terms.</p>

        <h2>5. Disclaimer of Warranties</h2>
        <p>
            The Application is provided "as is," without warranty of any kind. We do not warrant that the Application will meet your requirements or that it will be uninterrupted, secure, or error-free. The content generated by the AI may contain inaccuracies or errors and may not be unique. You are responsible for reviewing and validating all Generated Content before use.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
            In no event shall we be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Application.
        </p>

        <h2>7. Governing Law</h2>
        <p>
            These Terms shall be governed and construed in accordance with the laws of India, with the exclusive jurisdiction of the courts in Mumbai, Maharashtra.
        </p>
        
        <h2>8. Changes to Terms</h2>
        <p>
            We reserve the right to modify these terms at any time. We will notify you of any changes by posting the new Terms of Service on this page and updating the "Last Updated" date.
        </p>

        <h2>9. Contact Us</h2>
        <p>
            If you have any questions about these Terms, please contact us at: navaz@brandforge.me
        </p>
      </CardContent>
    </Card>
  );
}
